spring.application.name=auth-service-bolivia
server.port=8081

# Deshabilitar JPA ya que no usamos base de datos
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Configuración para el servicio de autenticación
app.name=Librería Páginas de Bolivia - Auth Service
app.version=1.0.0

# VULNERABILIDAD DE PRUEBA - Credenciales hardcodeadas
admin.password=123456
api.secret.key=123456
jwt.secret=mi_clave_secreta_super_segura_123456